function row = makeRow(simID, actionType, targetName, targetID, level, ...
                       entityName, entityID, g0, g1)
% makeRow
% -------
% Purpose:
%   Build one result row for the table from original vs edited GIC values.
%
% Definitions:
%   g0, g1 are scalars already reduced to a single number for that entity and time index.
%   We use absolute values for "Δ|GIC|" as you specified.
%
% Returns:
%   A struct suitable for table conversion/appending.

    deltaAbs = abs(g1) - abs(g0);
    % Percent change vs original *max* (protect div-by-zero)
    if abs(g0) > 0
        pctChangeMax = 100 * (abs(g1) - abs(g0)) / abs(g0);
    else
        pctChangeMax = NaN;
    end

    row = struct( ...
        'SimID',           simID, ...
        'ActionType',      string(actionType), ...
        'TargetName',      string(targetName), ...
        'TargetID',        targetID, ...
        'Level',           string(level), ...                 % 'substation' or 'transformer'
        'EntityName',      string(entityName), ...
        'EntityID',        entityID, ...
        'GIC_Orig_A',      g0, ...
        'GIC_Edit_A',      g1, ...
        'DeltaAbs_A',      deltaAbs, ...
        'PctChange_max',   pctChangeMax, ...
        'Z_forHeatmap_A',  deltaAbs ...
    );
end
