function row = makeRowNB(simID, actionType, targetName, targetID, level, entityName, entityID, ...
                         g0_avg, g1_avg, dAvg, pctMax)
% Store the average values & deltas for a single entity and change

row = struct( ...
    'SimID',          simID, ...
    'ActionType',     string(actionType), ...
    'TargetName',     string(targetName), ...
    'TargetID',       targetID, ...
    'Level',          string(level), ...           % 'transformer' or 'substation'
    'EntityName',     string(entityName), ...
    'EntityID',       entityID, ...
    'AvgAbs_Orig_A',  g0_avg, ...
    'AvgAbs_Edit_A',  g1_avg, ...
    'AvgDeltaAbs_A',  dAvg, ...                    % this is the Z value to plot
    'MaxPctChange',   pctMax ...                   % used for % threshold filter
);
end
