function plotSandboxComparison(theta,...
    I_indResults,I_indResultsOld,...
    GICLinesResults,GICLinesResultsOld,...
    GICSubsResults,GICSubsResultsOld,...
    app)

theta = theta(:);

%-------------------------------------------------------
% Nothing to compare
%-------------------------------------------------------
if isempty(I_indResultsOld) || ...
   isempty(GICLinesResultsOld) || ...
   isempty(GICSubsResultsOld)
    return
end

%-------------------------------------------------------
% Figure
%-------------------------------------------------------
figure(...
    'Color','w',...
    'Name','Sandbox Comparison',...
    'NumberTitle','off');

t = tiledlayout(3,1,...
    'TileSpacing','compact',...
    'Padding','compact');

%=======================================================
% Induced Current
%=======================================================
ax1 = nexttile;

plotComparison(...
    ax1,...
    theta,...
    I_indResults,...
    I_indResultsOld,...
    app.SandboxL,...
    app.OldSandboxL,...
    'Induced Current (A)',...
    'Induced Current');

%=======================================================
% Line GIC
%=======================================================
ax2 = nexttile;

plotComparison(...
    ax2,...
    theta,...
    GICLinesResults,...
    GICLinesResultsOld,...
    app.SandboxL,...
    app.OldSandboxL,...
    'Line GIC (A)',...
    'Line GIC');

%=======================================================
% Substation GIC
%=======================================================
ax3 = nexttile;

plotComparison(...
    ax3,...
    theta,...
    GICSubsResults,...
    GICSubsResultsOld,...
    app.SandboxS,...
    app.OldSandboxS,...
    'Substation GIC (A)',...
    'Substation GIC');

xlabel(ax3,'E-Field Orientation (deg)')

%-------------------------------------------------------
% Common formatting
%-------------------------------------------------------
linkaxes([ax1 ax2 ax3],'x')

xlim([min(theta) max(theta)])

xticks(ax1,0:30:max(theta))
xticks(ax2,0:30:max(theta))
xticks(ax3,0:30:max(theta))

end